<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260927104015 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Orders, journal, webhook deduplication, channel state, Messenger queue and rate-limiter storage.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE channel_states (cursor TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reconcile_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, throttled_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paused BOOLEAN NOT NULL, last_poll_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_poll_outcome VARCHAR(16) DEFAULT NULL, code VARCHAR(32) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE journal (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, channel VARCHAR(32) DEFAULT NULL, type VARCHAR(48) NOT NULL, severity VARCHAR(8) NOT NULL, message TEXT NOT NULL, context JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX journal_occurred_at ON journal (occurred_at)');
        $this->addSql('CREATE INDEX journal_severity ON journal (severity, id)');
        $this->addSql('CREATE TABLE orders (id UUID NOT NULL, channel VARCHAR(32) NOT NULL, external_id VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, currency VARCHAR(3) NOT NULL, total_minor INT NOT NULL, lines JSON NOT NULL, buyer_display_name VARCHAR(128) NOT NULL, external_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, external_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT NOT NULL, first_source VARCHAR(16) NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX orders_last_changed_at ON orders (last_changed_at)');
        $this->addSql('CREATE UNIQUE INDEX orders_channel_external_id ON orders (channel, external_id)');
        $this->addSql('CREATE TABLE webhook_events (channel VARCHAR(32) NOT NULL, event_id VARCHAR(128) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (channel, event_id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('CREATE TABLE cache_items (item_id VARCHAR(255) NOT NULL, item_data BYTEA NOT NULL, item_lifetime INT DEFAULT NULL, item_time INT NOT NULL, PRIMARY KEY (item_id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE channel_states');
        $this->addSql('DROP TABLE journal');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE webhook_events');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE cache_items');
    }
}
